"""Generated module: example

This module was automatically generated by Axiomander.
Entry point: absolute_value
Components: 1
"""

from .absolute_value import *

__all__ = [
    "absolute_value",
]

def main():
    """Main entry point for the example module."""
    # Example usage of absolute_value
    result = absolute_value(5)
    print(f'Result: {result}')
    return result